[Eth]
NetworkId = 25821
TrieTimeout = 150000000000
RPCGasCap = 20000000

[Eth.Miner]
GasCeil = 70000000
GasPrice = 100000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 100000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
DataDir = "./data"
IPCPath = "geth.ipc"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPModules = ["eth","net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
DiscoveryV5 = true
StaticNodes = []
BootstrapNodes = ["enode://e06ffdc4b9834fbcbba7c7470dc29a699ef9d9bf59435a38b3f5777eba26ab714f7eaf45a9af40ba9dbb332488a6e8328db75431707f9a0da92d65074913398d@13.214.198.137:30301"]
ListenAddr = "0.0.0.0:30303"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "h2.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
RotateHours = 1                  
MaxBackups = 168           
